### ISSUE TITLE
Graph across labels rather than time

### ISSUE THREAD

**Issue by asomers** [telekom/sebastiangunreben-cdf-plugin#3]
I'd like to view a CDF of an Instant query which returns multiple series differing by their label.  For this query, there isn't any time axis.  Can I use your plugin to draw such a graph?  The query data would look like this:

time | value[id="X"] | value[id="Y"] | value[id="Z"] | value[id="W"]
-- | -- | -- | -- | --
t1 | 1 | 5 | 3 | 2

**Comment by sebastiangunreben** [comment]
Hi,

the cdf plugin will draw per each series a CDF within the same graph.
The time field will by anyhow dropped, so there are no daubts that it will not work.

BR,
Sebastian
Von: Alan Somers ***@***.***>
Gesendet: Dienstag, 7. Februar 2023 21:55
An: telekom/sebastiangunreben-cdf-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [telekom/sebastiangunreben-cdf-plugin] Graph across labels rather than time (Issue #3)


I'd like to view a CDF of an Instant query which returns multiple series differing by their label. For this query, there isn't any time axis. Can I use your plugin to draw such a graph? The query data would look like this:
time
value[id="X"]
value[id="Y"]
value[id="Z"]
value[id="W"]
t1
1
5
3
2
